name: SonarQube
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  sonarqube:
    runs-on: [ self-hosted, linux ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        run: sonar-scanner -Dsonar.projectKey=softserve-eventsexpress-nodejs -Dsonar.projectName=softserve-EventsExpress_Node_js -Dsonar.sources=. "-Dsonar.exclusions=**/node_modules/**"
